openapi: "3.0.2"
info:
  title: Metastore
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /metastore:
    post:
      summary: Add a new metastore
      tags:
       - lake-sharing
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                comment:
                  type: string
                type:
                  type: string
                  enum:
                    - glue
                    - hive2
                    - hive3
                    - iceberg_hadoop
                    - iceberg_hive
                    - iceberg_jdbc
                    - iceberg_nessie
                properties:
                  anyOf:
                    - $ref: "#/components/schemas/GlueProperties"
                    - $ref: "#/components/schemas/Hive2Properties"
                    - $ref: "#/components/schemas/Hive3Properties"
                    - $ref: "#/components/schemas/IcebergHadoopProperties"
                    - $ref: "#/components/schemas/IcebergJdbcProperties"
                    - $ref: "#/components/schemas/IcebergNessieProperties"
                skipValidation:
                  type: boolean
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Metastore"
        "403":
          description: Storage already exists
    get:
      summary: list all metastores
      tags:
       - lake-sharing
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: 
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Metastore"
  /metastore/{id}:
    patch:
      summary: update an existing metastore
      tags:
       - lake-sharing
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                comment:
                  type: string
                owner:
                  type: string
                type:
                  type: string
                properties:
                  anyOf:
                    - $ref: "#/components/schemas/GlueProperties"
                    - $ref: "#/components/schemas/Hive2Properties"
                    - $ref: "#/components/schemas/Hive3Properties"
                    - $ref: "#/components/schemas/IcebergHadoopProperties"
                    - $ref: "#/components/schemas/IcebergJdbcProperties"
                    - $ref: "#/components/schemas/IcebergNessieProperties"
                skipValidation:
                  type: boolean
                force:
                  type: boolean
      responses:
        "200":
          description: OK, metastore updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Metastore"
        "404":
          description: "Metastore not found"
    delete:
      summary: delete a metastore
      tags:
       - lake-sharing
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: force
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: deleted
        "404":
          description: metastore does not exists
    get:
      tags:
       - lake-sharing
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Metastore"
        "404":
          description: Metastore does not exist
  /metastore/{id}/validate:
    post:
      tags:
       - lake-sharing
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    enum:
                      - success
                      - failure
                  message:
                    type: string
    
components:
  schemas:
    Hive2Properties:
      type: object
      properties: {}
    Hive3Properties:
      type: object
      properties: {}
    GlueProperties:
      type: object
      properties:
        catalogId:
          type: string
        credentials:
          $ref: "common.yaml#/components/schemas/SimpleAwsCredentials"
    IcebergHadoopProperties:
      type: object
      properties: {}
    IcebergJdbcProperties:
      type: object
      properties: {}
    IcebergNessieProperties:
      type: object
      properties: {}
    Metastore:
      type: object
      properties:
        name:
          type: string
        comment:
          type: string
        owner:
          type: string
        id:
          type: string
        type:
          type: string
        properties:
          anyOf:
            - $ref: "#/components/schemas/GlueProperties"
            - $ref: "#/components/schemas/Hive2Properties"
            - $ref: "#/components/schemas/Hive3Properties"
            - $ref: "#/components/schemas/IcebergHadoopProperties"
            - $ref: "#/components/schemas/IcebergJdbcProperties"
            - $ref: "#/components/schemas/IcebergNessieProperties"
        validatedAt:
          type: integer
          format: int64
        createdAt:
          type: integer
          format: int64
        createdBy:
          type: string
        updatedAt:
          type: integer
          format: int64
        updatedBy:
          type: string
