openapi: "3.0.2"
info:
  title: Storage
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /storage:
    post:
      summary: Add a new storage
      tags:
       - lake-sharing
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                comment:
                  type: string
                type:
                  type: string
                  enum:
                    - gcs
                    - s3
                    - abfs
                credentials:
                  oneOf:
                    - $ref: "common.yaml#/components/schemas/SimpleAwsCredentials"
                uri:
                  type: string
                  example: s3://my-nice-bucket/some/prefix
                skipValidation:
                  type: boolean
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Storage"
        "403":
          description: Storage already exists
    get:
      summary: List storage
      tags:
       - lake-sharing
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: 
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Storage"

  /storage/{id}:
    patch:
      summary: Update an existing storage
      tags:
       - lake-sharing
      parameters:
        - required: true
          name: id
          in: path
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                comment:
                  type: string
                type:
                  type: string
                  enum:
                    - gcs
                    - s3
                    - abfs
                credentials:
                  oneOf:
                    - $ref: "common.yaml#/components/schemas/SimpleAwsCredentials"
                uri:
                  type: string
                  example: s3://my-nice-bucket/some/prefix
                skipValidation:
                  type: boolean
                force:
                  type: boolean
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Storage"
        "404":
          description: Storage does not exists
    delete:
      summary: Delete an existing storage
      tags:
       - lake-sharing
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
        - name: force
          required: false
          in: query
          schema:
            type: string
      responses:
        "200":
          description: deleted
        "404":
          description: Storage does not exists
    get:
      summary: Describe storage
      tags:
       - lake-sharing
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Storage"
        "404":
          description: Storage does not exist
  /storage/{id}/validate:
    post:
      summary: Validate an existing storage
      tags:
       - lake-sharing
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  result: 
                    type: string
                    enum:
                      - success
                      - failure
                  message:
                    type: string
        "404":
          description: storage does not exist
        

components:
  schemas:
    Storage:
      type: object
      properties:
        name:
          type: string
        comment:
          type: string
        owner:
          type: string
        id:
          type: string
        type:
          type: string
        uri:
          type: string
          example: s3://my-nice-bucket/some/prefix
        validatedAt:
          type: integer
          format: int64
        createdAt:
          type: integer
          format: int64
        createdBy:
          type: string
        updatedAt:
          type: integer
          format: int64
        updatedBy:
          type: string
