name: Run Gradle on PRs
on: pull_request
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run:  |
              if [ "$RUNNER_OS" == "Windows" ]; then
                export HADOOP_HOME="$(pwd)/.github/workflows/hadoop3-win-binaries"
              fi
              ./gradlew build testNative --no-daemon
        shell: bash