name: Run Spectral
on:
  pull_request:
    branches-ignore: []
  push:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      # Check out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Install Spectral
      - id: install_spectral
        run: npm install -g @stoplight/spectral-cli

      # Run Spectral
      - id: run_spectral
        run: spectral lint ./protocol/*.{yml,yaml} --fail-severity=info