name: Run Spectral
on:
  - pull_request
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      # Check out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Install Spectral
      - id: install_spectral
        run: npm install -g @stoplight/spectral-cli

      # Run Spectral
      - id: run_spectral
        run: spectral lint ./docs/protocol/*.{yml,yaml} --fail-severity=info